### ISSUE TITLE
Self-hosted MacOS M1 CI outage with broken conda environment

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#112877]
## Current Status
Ongoing

## Error looks like
MacOS M1 jobs all fail due to missing packages

## Incident timeline (all times pacific)
Nov 2nd 2023

## User impact
MacOS M1 jobs are not run

## Root cause
TBD

## Mitigation
Jobs have been marked as unstable:
* https://github.com/pytorch/pytorch/issues/112832
* https://github.com/pytorch/pytorch/issues/102299

## Prevention/followups
TBD

**Comment by glennwester** [comment]
GitHub Team is actively investigating.

**Comment by glennwester** [comment]
Statuses are Green now, you should no longer see an issue https://www.githubstatus.com/

**Comment by malfet** [comment]
Hi @glennwester thank you very much, but this outage is related to our own self-hosted runner, which is still ongoing, let me update the title to clarify that

**Comment by malfet** [comment]
There is something really weird with the cache action.
Comparing [successful run](https://github.com/pytorch/pytorch/actions/runs/6749031264/job/18348848874) with [failed run](https://github.com/pytorch/pytorch/actions/runs/6749031264/job/18348849163) on the same commit:
```
path: /Users/ec2-user/runner/_work/_temp/miniconda
    key: miniconda-macOS-ARM64-3.9.12-202[31](https://github.com/pytorch/pytorch/actions/runs/6749031264/job/18348849163#step:6:33)103d
    enableCrossOsArchive: false
    fail-on-cache-miss: false
    lookup-only: false
  env:
    GIT_DEFAULT_BRANCH: main
    BUILD_ENVIRONMENT: macos-12-py3-arm64
    TEST_CONFIG: default
    SHARD_NUMBER: 2
    NUM_TEST_SHARDS: 3
    PR_BODY: 
    PYTORCH_RETRY_TEST_CASES: 1
    PYTORCH_OVERRIDE_FLAKY_SIGNAL: 1
Received 225124721 of 225124721 (100.0%), 214.1 MBs/sec
Cache Size: ~215 MB (225124721 B)
```
vs
```
    path: /Users/ec2-user/runner/_work/_temp/miniconda
    key: miniconda-macOS-ARM64-3.9.12-202[31](https://github.com/pytorch/pytorch/actions/runs/6749031264/job/18348848874#step:6:33)103d
    enableCrossOsArchive: false
    fail-on-cache-miss: false
    lookup-only: false
  env:
    GIT_DEFAULT_BRANCH: main
    BUILD_ENVIRONMENT: macos-12-py3-arm64
    TEST_CONFIG: default
    SHARD_NUMBER: 1
    NUM_TEST_SHARDS: 3
    PR_BODY: 
    PYTORCH_RETRY_TEST_CASES: 1
    PYTORCH_OVERRIDE_FLAKY_SIGNAL: 1
Received 352[32](https://github.com/pytorch/pytorch/actions/runs/6749031264/job/18348848874#step:6:34)1536 of 365349546 (96.4%), [33](https://github.com/pytorch/pytorch/actions/runs/6749031264/job/18348848874#step:6:35)5.7 MBs/sec
Cache Size: ~[34](https://github.com/pytorch/pytorch/actions/runs/6749031264/job/18348848874#step:6:36)8 MB ([36](https://github.com/pytorch/pytorch/actions/runs/6749031264/job/18348848874#step:6:38)5349546 B)
```
