### ISSUE TITLE
`aten.upsample_nearest2d.vec` is in core ATen IR and should not be decomposed

### ISSUE THREAD

**Issue by jgong5** [pytorch/pytorch#116684]
### 🐛 Describe the bug

`aten.upsample_nearest2d.vec` is part of the Aten core IR (https://pytorch.org/docs/main/torch.compiler_ir.html). But it also appears in the decomposition and registered with "CompositeImplicitAutograd" key at here https://github.com/pytorch/pytorch/blob/3fe437b24ba70e0ac7af8b6664c66875cf91731b/torch/_decomp/decompositions.py#L2437.

This would break some backend compiler that expects `aten.upsample_nearest2d.vec` to be in the FX IR and has rules to work on it.

### Versions

PyTorch mainline version: 3fe437b24ba70e0ac7af8b6664c66875cf91731b

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @SherlockNoMad @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by lezcano** [comment]
`.vec` decomps should not be marked as core IR, as they are just sugar (they are even CompositeImplicit). cc @SS-JIA

**Comment by lezcano** [comment]
cc @larryliu0820

**Comment by satheeshhab** [comment]
upsample_bilinear2d.vec is another upsample variant which is having the same decomposition issue.

**Comment by lezcano** [comment]
cc @SherlockNoMad

**Comment by larryliu0820** [comment]
I believe this decomposition should be removed. cc @SS-JIA

**Comment by larryliu0820** [comment]
We should also change the kernel to be using `CompositeExplicitAutograd` dispatch key

**Comment by lezcano** [comment]
Why not remove it from core?

**Comment by larryliu0820** [comment]
> Why not remove it from core?

Remove what?

**Comment by lezcano** [comment]
This function and its default variant have a decomposition, why do we want them to be part of ATen core?

**Comment by larryliu0820** [comment]
Oh I see, I think that makes sense. I will keep a note on this function and get back to this issue after we make a decision.

**Comment by jgong5** [comment]
> This function and its default variant have a decomposition, why do we want them to be part of ATen core?

Then, should we leave `upsample_nearest2d` in the core Aten IR? It is also decomposed now: https://github.com/pytorch/pytorch/blob/91bbcf8c718ff245ec85e33874dc4c1a1a28c4f3/torch/_decomp/decompositions.py#L2561

**Comment by lezcano** [comment]
My point is that we can decompose upsample nearest 2d (both default and vec) following the decomposition we already have. cc @vfdev-5 who has been working on these ops

**Comment by jgong5** [comment]
> My point is that we can decompose upsample nearest 2d (both default and vec) following the decomposition we already have. cc @vfdev-5 who has been working on these ops

Can we leave the decision whether to decompose these ops to the backend? Different backends might work on different levels of the graph. Some prefer to work on the high-level FX IR and want to see these ops not decomposed.

**Comment by gmagogsfm** [comment]
> > My point is that we can decompose upsample nearest 2d (both default and vec) following the decomposition we already have. cc @vfdev-5 who has been working on these ops
> 
> Can we leave the decision whether to decompose these ops to the backend? Different backends might work on different levels of the graph. Some prefer to work on the high-level FX IR and want to see these ops not decomposed.

Right now because of how .vec variant is registered (at `CompositeImplicitAutograd` key), I don't think it is possible to disable the decomposition. But we are working on allowing more control on decomposition so even `CompositeImplicitAutograd` ops can be removed from decomposition. @tugsbayasgalan 

Once that is done, you can tweak the `decomp_table` argument to change decomposition behavior.

https://github.com/pytorch/pytorch/blob/92cf7ba36b33f2b40a0321bdbe75356bcd7946fc/torch/export/exported_program.py#L369

**Comment by BowenBao** [comment]
Hi @gmagogsfm, I'm also experiencing this and a similar issue #115883. Will the decomposition there also be avoidable in the future?

**Comment by aifartist** [comment]
@bdhirsh @gmagogsfm @BowenBao 
https://github.com/pytorch/pytorch/issues/116848
I'm not sure if these problems are related but a change was made on Nov 21(1f8d00c) to call aten.upsample_nearest2d.default and this aten version of the function just returns garbage if **inference_mode** and **torch.compile** are used.  Instead of:
> tensor([[[[1., 2.], [3., 4.]]]])
being upsampled to:
> tensor([[[[1., 1., 2., 2.],
          [1., 1., 2., 2.],
          [3., 3., 4., 4.],
          [3., 3., 4., 4.]]]])
the output is garbage.

**Comment by jgong5** [comment]
> Right now because of how .vec variant is registered (at `CompositeImplicitAutograd` key), I don't think it is possible to disable the decomposition. But we are working on allowing more control on decomposition so even `CompositeImplicitAutograd` ops can be removed from decomposition. @tugsbayasgalan
> 
> Once that is done, you can tweak the `decomp_table` argument to change decomposition behavior.

@gmagogsfm @tugsbayasgalan May I know if there is any progress on this? Thanks!

**Comment by rkazants** [comment]
Hi  @jgong5 @lezcano @satheeshhab @larryliu0820 @gmagogsfm @tugsbayasgalan @aifartist @bdhirsh, @BoyuanFeng,

this case is still reproducible,

```py
import torch
import torch.nn.functional as F

class NeuralNetwork(torch.nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()

    def forward(self, hidden_states):
        return F.interpolate(hidden_states, scale_factor=2.0, mode="nearest")

ep = torch.export.export(NeuralNetwork(), (torch.zeros(1, 3, 20, 20),))

ep = ep.run_decompositions(decomp_table={})
```

output:

```
ExportedProgram:
    class GraphModule(torch.nn.Module):
        def forward(self, hidden_states: "f32[1, 3, 20, 20]"):
            # File: C:\Users\rkazants\Intel\cvs_issues\149983_export_issue\repro_simple.py:9 in forward, code: return F.interpolate(hidden_states, scale_factor=2.0, mode="nearest")
            _to_copy: "f32[1, 3, 20, 20]" = torch.ops.aten._to_copy.default(hidden_states, dtype = torch.float32);  hidden_states = None
            arange: "f32[40]" = torch.ops.aten.arange.default(40, dtype = torch.float32, device = device(type='cpu'), pin_memory = False)
            add: "f32[40]" = torch.ops.aten.add.Tensor(arange, 0.0);  arange = None
            mul: "f32[40]" = torch.ops.aten.mul.Tensor(add, 0.5);  add = None
            _to_copy_1: "i64[40]" = torch.ops.aten._to_copy.default(mul, dtype = torch.int64);  mul = None
            unsqueeze: "i64[40, 1]" = torch.ops.aten.unsqueeze.default(_to_copy_1, -1);  _to_copy_1 = None
            arange_1: "f32[40]" = torch.ops.aten.arange.default(40, dtype = torch.float32, device = device(type='cpu'), pin_memory = False)
            add_1: "f32[40]" = torch.ops.aten.add.Tensor(arange_1, 0.0);  arange_1 = None
            mul_1: "f32[40]" = torch.ops.aten.mul.Tensor(add_1, 0.5);  add_1 = None
            _to_copy_2: "i64[40]" = torch.ops.aten._to_copy.default(mul_1, dtype = torch.int64);  mul_1 = None
            _unsafe_index: "f32[1, 3, 40, 40]" = torch.ops.aten._unsafe_index.Tensor(_to_copy, [None, None, unsqueeze, _to_copy_2]);  _to_copy = unsqueeze = _to_copy_2 = None
            _to_copy_3: "f32[1, 3, 40, 40]" = torch.ops.aten._to_copy.default(_unsafe_index, dtype = torch.float32);  _unsafe_index = None
            return (_to_copy_3,)
```

Without calling `run_decompositions`, I observe `torch.ops.aten.upsample_nearest2d.vec`.

Best regards,
Roman
