### ISSUE TITLE
More structured alternative to native_functions.yaml

### ISSUE THREAD

**Issue by LaurentMazare** [pytorch/pytorch#12417]
## 🚀 Feature

[native_functions.yaml](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/native_functions.yaml) provides a list of supported tensor functions/methods in YAML. The function description is given as a string, e.g. 
```
- func: add(Tensor self, Tensor other, *, Scalar alpha=1) -> Tensor
```
Maybe would it make sense to support a more structured version so that tools don't have to parse these strings.

## Motivation

I'm currently writing [ocaml-pytorch](https://github.com/LaurentMazare/ocaml-torch) some experimental OCaml bindings for the C++ API of PyTorch.

It's working pretty well so far, as there are lots of functions in the C++ tensor API, some of the bindings boilerplate code gets automatically generated from `native_functions.yaml`.

## Pitch
Parsing the function description is a bit cumbersome. As an alternative, the yaml file (or some other files) could contain a more structured version of the same data. E.g instead of:
```
- func: add(Tensor self, Tensor other, *, Scalar alpha=1) -> Tensor
```
Something like:
```
- funcname: add
  args:
    - argname: self
      argtype: Tensor
    - argname: other
      argtype: Tensor
    - argname: alpha
      argtype: Scalar
      default: 1
  returns: Tensor
```

## Alternatives

Maybe there are some other files that can currently be scraped to obtain the same information. Reading directly `Tensor.h` would also be possible but not ideal as it's using the C syntax.
