### ISSUE TITLE
docker pytorch cuda

### ISSUE THREAD

**Issue by Jaroslove** [pytorch/pytorch#133692]
### 🐛 Describe the bug

Hi all,
I use Windows 11 as my host, got nvidia drivers and pytorch with cuda (both 12.1 and 12.4 versions) works perfectly.
When I try to run a docker container FROM pytorch/pytorch:2.4.0-cuda12.1-cudnn9-devel (as an example, I tried a lot more images)
in my container I see nvidia-smi

![nvidia_smi_driver](https://github.com/user-attachments/assets/b5e697fa-28f9-4902-8936-9db3dadee16e)

Follow command `torch.version.cuda` returns **'12.1'**
command `torch.cuda.device_count()` returns **1**
but the command `torch.cuda.is_available()` returns an error:
###   return torch._C._cuda_getDeviceCount() > 0

If I try to use the command `torch.cuda.is_available()` again, there is on error but result is **False**

I searched some similar issue and tried to set `os.environ['CUDA_VISIBLE_DEVICES'] = "0"` it didn't help me

### Versions

torch.version.cuda -> '12.1'
torch.__version__ -> '2.4.0'
nncv --version
  nvcc: NVIDIA (R) Cuda compiler driver
  Copyright (c) 2005-2023 NVIDIA Corporation
  Built on Mon_Apr__3_17:16:06_PDT_2023
  Cuda compilation tools, release 12.1, V12.1.105
  Build cuda_12.1.r12.1/compiler.32688072_0

**Comment by yanqiangmiffy** [comment]
how do you solve the problem ,now i have ths same issuse

**Comment by Jaroslove** [comment]
> how do you solve the problem ,now i have ths same issuse

I pointed my GPU in docker compose file like that:
```
services:
  test:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
```
