### ISSUE TITLE
[export] Strict-export fails with list of modules

### ISSUE THREAD

**Issue by angelayi** [pytorch/pytorch#150428]
### 🐛 Describe the bug

([x-post from internal](https://fb.workplace.com/groups/pytorch.edge.users/permalink/1732340610969558/))

```python
    def test_list_model(self):
        class A(torch.nn.Module):
            def __init__(self):
                super().__init__()
                self.a = torch.nn.Parameter(torch.ones(3, 3))

            def forward(self, x):
                return x + self.a 
        
        class M(torch.nn.Module):
            def __init__(self):
                super().__init__()
                self.models = [A(), A()]
            
            def forward(self, x):
                for m in self.models:
                    x = m(x)
                return x 
        
        inp = (torch.ones(3, 3),)
        M()(*inp)
        ep = torch.export.export(M(), inp, strict=True)
        print(ep)
```

Strict-export fails with:
```
  File "/data/users/angelayi/pytorch/torch/export/_trace.py", line 1981, in _export_for_training
    export_artifact = export_func(
  File "/data/users/angelayi/pytorch/torch/export/_trace.py", line 1475, in _strict_export
    _replace_param_buffer_names(param_buffer_table, export_graph_signature)
  File "/data/users/angelayi/pytorch/torch/export/_trace.py", line 271, in _replace_param_buffer_names
    spec.target = param_buffer_table[spec.target]
KeyError: 'L__self___models_0_a
```

Non-strict considers the parameters as constant tensors:
```
ExportedProgram:
    class GraphModule(torch.nn.Module):
        def forward(self, c_lifted_tensor_0: "f32[3, 3]", c_lifted_tensor_1: "f32[3, 3]", x: "f32[3, 3]"):
             # File: /data/users/angelayi/pytorch/moo.py:325 in forward, code: return x + self.a
            add: "f32[3, 3]" = torch.ops.aten.add.Tensor(x, c_lifted_tensor_0);  x = c_lifted_tensor_0 = None
            add_1: "f32[3, 3]" = torch.ops.aten.add.Tensor(add, c_lifted_tensor_1);  add = c_lifted_tensor_1 = None
            return (add_1,)
            
Graph signature: 
    # inputs
    c_lifted_tensor_0: CONSTANT_TENSOR target='lifted_tensor_0'
    c_lifted_tensor_1: CONSTANT_TENSOR target='lifted_tensor_1'
    x: USER_INPUT
    
    # outputs
    add_1: USER_OUTPUT
```

### Versions

main
