### ISSUE TITLE
[BUILD] Cannot detect CUDA when build from source

### ISSUE THREAD

**Issue by hieupth** [pytorch/pytorch#152592]
Hi, I am building from source using `rattler-build` with this `recipe.yaml`

```yaml
context:
  name: pytorch
  version: nightly
  rev: main
  python: 3.12
  gcc: 13.3
  cuda: 12.8
  cudnn: 9.8
  archs: 8.6;9.0;10.0;12.0;12.6

package:
  name: ${{name|lower}}
  version: ${{version}}

source:
  git: https://github.com/pytorch/pytorch.git
  rev: ${{rev}}

build:
  script:
    env:
      PACKAGE_TYPE: conda
      USE_SYSTEM_SLEEF: 1
      BUILD_CUSTOM_PROTOBUF: OFF
      USE_SYSTEM_PYBIND11: 1
      USE_SYSTEM_EIGEN_INSTALL: 1
      USE_MKLDNN: 1
      USE_CUDA: 1
      USE_CUFILE: 1
      TORCH_CUDA_ARCH_LIST: "${{archs}}"
      CUDA_HOME: $PREFIX/targets/x86_64-linux
      CUDAToolkit_BIN_DIR: $PREFIX/bin 
      CUDAToolkit_ROOT_DIR: $PREFIX
      CUDAToolkit_ROOT: $PREFIX
      CUDAToolkit_TARGET_DIR: $PREFIX/targets/x86_64-linux
      CMAKE_PREFIX_PATH: $PREFIX
      CMAKE_LIBRARY_PATH: $PREFIX/lib:$PREFIX/include:$CMAKE_LIBRARY_PATH
    content: |
      > third_party/NNPACK/cmake/DownloadSix.cmake
      $PYTHON setup.py install \
      --single-version-externally-managed \
      --record=record.txt \
      --prefix="$PREFIX"

requirements:
  build:
    - gcc=${{gcc}}
    - gxx=${{gcc}}
    - make
    - cmake
    - ninja
    - mkl-devel
    - libprotobuf
    - protobuf
    - nccl
    - cudnn=${{cudnn}}
    - cuda-toolkit=${{cuda}}
    - cuda-compiler=${{cuda}}
    - cuda-nvcc=${{cuda}}
    - cuda-driver-dev=${{cuda}}
    - cuda-cudart-dev=${{cuda}}
    - cuda-cupti-dev=${{cuda}}
    - cuda-nvrtc-dev=${{cuda}}
    - cuda-nvtx-dev=${{cuda}}
    - cuda-nvml-dev=${{cuda}}
    - cuda-profiler-api=${{cuda}}
    - cusparselt
    - libcublas-dev
    - libcudss-dev
    - libcufile-dev
    - libcufft-dev
    - libcurand-dev
    - libcusolver-dev
    - libcusparse-dev 
  host:
    - python=3.12
    - setuptools
    - pip
    - six
    - numpy
    - pyyaml
    - mkl-devel
    - typing-extensions
    - magma
    - nccl
    - cudnn=${{cudnn}}
    - cuda-toolkit=${{cuda}}
    - cuda-compiler=${{cuda}}
    - cuda-nvcc=${{cuda}}
    - cuda-driver-dev=${{cuda}}
    - cuda-cudart-dev=${{cuda}}
    - cuda-cupti-dev=${{cuda}}
    - cuda-nvrtc-dev=${{cuda}}
    - cuda-nvtx-dev=${{cuda}}
    - cuda-nvml-dev=${{cuda}}
    - cuda-profiler-api=${{cuda}}
    - cusparselt
    - libcublas-dev
    - libcudss-dev
    - libcufile-dev
    - libcufft-dev
    - libcurand-dev
    - libcusolver-dev
    - libcusparse-dev 
    - libabseil
    - libprotobuf
    - sleef
    - pybind11
    - eigen
    - zlib
  run:
    - python=3.12
    - mkl
    - numpy
    - pyyaml
    - libnuma
    - typing-extensions
    - cudnn=${{cudnn}}
    - cuda-toolkit=${{cuda}}
    - cuda-driver-dev=${{cuda}}

tests:
  - script:
    - python -c "
        import torch;
        print("is_available:", torch.cuda.is_available());
        print("Device name:", torch.cuda.get_device_name(0));
      "
```

I had been trying all the ways I found but it keep error like this:
```bash
-- Could NOT find CUDA (missing: CUDA_INCLUDE_DIRS) (found version "12.8")
 │ │ CMake Warning at cmake/public/cuda.cmake:31 (message):
 │ │   PyTorch: CUDA cannot be found.  Depending on whether you are building
 │ │   PyTorch or a PyTorch dependent library, the next warning / error will give
 │ │   you more info.
 │ │ Call Stack (most recent call first):
 │ │   cmake/Dependencies.cmake:44 (include)
 │ │   CMakeLists.txt:856 (include)
 │ │ 
 │ │ CMake Warning at cmake/Dependencies.cmake:76 (message):
 │ │   Not compiling with CUDA.  Suppress this warning with -DUSE_CUDA=OFF.
 │ │ Call Stack (most recent call first):
 │ │   CMakeLists.txt:856 (include)
```

My system is Debian, RTX5090 with Nvidia Driver 570.133.20. The nvidia-smi work correctly and I don't know what happened here. Please help!
