### ISSUE TITLE
`torch.export` fails with `KeyError` when `BatchNorm.running_mean` is read and modified, even when shape/value is unchanged

### ISSUE THREAD

**Issue by tinywisdom** [pytorch/pytorch#156167]
## Summary

When using `torch.export` to export a model that reads and modifies internal buffers (e.g., `BatchNorm.running_mean.zero_()`) during `forward()`, the process fails with:
```
KeyError: 'L__self___bn.running_mean'
```

However, if the line `output = self.bn(t1)` is commented out, the export proceeds normally — even though the exact same parameter and buffer accesses are present.

This suggests that:

1. Modifying running_mean during forward is not explicitly disallowed — but silently triggers export failure

2. The error message is confusing and unhelpful

3. There might be incomplete or inconsistent state tracking of internal buffer mutations inside forward

## Repro Steps (Minimal Script)
```python
import torch
import torch.nn as nn
from typing import List

class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Conv2d(3, 8, 1, stride=1, padding=1)
        self.bn = nn.BatchNorm2d(8)
        self.bn.eval()
        self.init_components: List[nn.Module] = [self.conv, self.bn]

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        t1 = self.conv(x)
        print("Before BN:")
        for name, buf in self.bn.named_buffers():
            print(f"{name}: {buf.shape}, {buf}")

        output = self.bn(t1)  # ← Commenting this out avoids the KeyError

        print("After BN:")
        for name, buf in self.bn.named_buffers():
            print(f"{name}: {buf.shape}, {buf}")
        
        # Modifying buffer in-place (no shape change)
        self.bn.running_mean.zero_()
        return output

model = MyModel()
input_tensor = torch.randn(1, 3, 32, 32)

model.eval()
with torch.no_grad():
    output = model(input_tensor)

# This line triggers KeyError
torch.export.export(model, (input_tensor,))
```

Fails with:
```
KeyError: 'L__self___bn.running_mean'
```

## Technical Observations
+ The buffer exists and is printed both before and after the call to` self.bn(t1)`

+ Export seems to track the buffer name `'L__self___bn.running_mean'`, but fails to find it during _rewrite_dynamo_tensor_constants

+ Commenting out `output = self.bn(t1)` — even though the same buffer is still accessed — prevents the crash, suggesting a non-robust trace path resolution

+ This implies export’s symbolic tracing is sensitive to usage context, and may not detect side-effects that occur post graph-capture

## Expected Behavior
+ If modifying `.running_mean` in `forward()` is not allowed during export, a clear and early error message should be provided.
+ If PyTorch allows it (e.g. because shape/type doesn’t change), then export should succeed or handle it gracefully.
+ The buffer is not dynamically created, and its value is only zeroed-out. There is no structural change, so failure is unexpected.

### Versions

<details> <summary>Click to expand envs</summary>

```
PyTorch version: 2.7.1a0+gite2d141d
Is debug build: True
CUDA used to build PyTorch: 12.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.16 (main, Dec 11 2024, 16:24:50) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-6.8.0-59-generic-x86_64-with-glibc2.35
Is CUDA available: True
```

</details>

**Comment by yiming0416** [comment]
Hi @tinywisdom, I cannot repro this issue on main. It works fine and I got the following exported program by running the script you provided:

```
ExportedProgram:
    class GraphModule(torch.nn.Module):
        def forward(self, p_conv_weight: "f32[8, 3, 1, 1]", p_conv_bias: "f32[8]", p_bn_weight: "f32[8]", p_bn_bias: "f32[8]", b_bn_running_mean: "f32[8]", b_bn_running_var: "f32[8]", b_bn_num_batches_tracked: "i64[]", x: "f32[1, 3, 32, 32]"):
             # File: /data/users/yimingzhou/pytorch/torch/nn/modules/conv.py:548 in forward, code: return self._conv_forward(input, self.weight, self.bias)
            conv2d: "f32[1, 8, 34, 34]" = torch.ops.aten.conv2d.default(x, p_conv_weight, p_conv_bias, [1, 1], [1, 1]);  x = p_conv_weight = p_conv_bias = None
            
             # File: /data/users/yimingzhou/pytorch/torch/nn/modules/batchnorm.py:193 in forward, code: return F.batch_norm(
            batch_norm: "f32[1, 8, 34, 34]" = torch.ops.aten.batch_norm.default(conv2d, p_bn_weight, p_bn_bias, b_bn_running_mean, b_bn_running_var, False, 0.1, 1e-05, True);  conv2d = p_bn_weight = p_bn_bias = b_bn_running_var = None
            
             # File: /data/users/yimingzhou/pytorch/demo.py:58 in forward, code: self.bn.running_mean.zero_()
            zero_: "f32[8]" = torch.ops.aten.zero_.default(b_bn_running_mean);  b_bn_running_mean = zero_ = None
            return (batch_norm,)
            
Graph signature: 
    # inputs
    p_conv_weight: PARAMETER target='conv.weight'
    p_conv_bias: PARAMETER target='conv.bias'
    p_bn_weight: PARAMETER target='bn.weight'
    p_bn_bias: PARAMETER target='bn.bias'
    b_bn_running_mean: BUFFER target='bn.running_mean' persistent=True
    b_bn_running_var: BUFFER target='bn.running_var' persistent=True
    b_bn_num_batches_tracked: BUFFER target='bn.num_batches_tracked' persistent=True
    x: USER_INPUT
    
    # outputs
    batch_norm: USER_OUTPUT
    
Range constraints: {}
```
