### ISSUE TITLE
Remove TensorOptions logic from generated code

### ISSUE THREAD

**Issue by izdeby** [pytorch/pytorch#26428]
Scripts that are generating code are getting more and more complex and require a lot of domain knowledge in order to make any substantial changes. This is mostly due to logic around TensorOptions. We should eliminate it in order to significanlty decrease complexity of the code.

I will show my proposal on example of one of the methods and show all generated files with original (current master) code and proposed one. 

### native_functions.yaml
- func: bartlett_window(int window_length, *, ScalarType? dtype=None, Layout? layout=None, Device? device=None, bool? pin_memory=None) -> Tensor`

### Declarations.yaml
This is the central generated file. Declarations defined here will be used in almost all downstream scripts. 

**Proposed change:** 
- get rid of TensorOptions as a dymamic_type and replace it with expanded list of arguments: dtype, device, layout, pin_memory.

**Example:**
declarations.yaml original
```
- name: bartlett_window
  operator_name: bartlett_window
  overload_name: ''
  use_c10_dispatcher: false
  matches_jit_signature: true
  schema_string: aten::bartlett_window(int window_length, *, ScalarType? dtype=None, Layout? layout=None, Device? device=None, bool? pin_memory=None) -> Tensor
  method_prefix_derived: ''
  arguments:
  - annotation: null
    dynamic_type: int64_t
    is_nullable: false
    name: window_length
    type: int64_t
  - annotation: null
    default: '{}'
    dynamic_type: TensorOptions
    is_nullable: false
    kwarg_only: true
    name: options
    type: const TensorOptions &
  method_of:
  - Type
  - namespace
  mode: native
  python_module: ''
  returns:
  - dynamic_type: Tensor
    name: result
    type: Tensor
  inplace: false
  is_factory_method: true
  abstract: false
  requires_tensor: false
  device_guard: true
  with_gil: false
  deprecated: false
```

declarations.yaml proposed
```
- name: bartlett_window
  operator_name: bartlett_window
  overload_name: ''
  use_c10_dispatcher: false
  matches_jit_signature: true
  schema_string: aten::bartlett_window(int window_length, *, ScalarType? dtype=None, Layout? layout=None, Device? device=None, bool? pin_memory=None) -> Tensor
  method_prefix_derived: ''
  arguments:
  - annotation: null
    dynamic_type: int64_t
    is_nullable: false
    name: window_length
    type: int64_t
  - annotation: null
    default: c10::nullopt
    dynamic_type: ScalarType
    is_nullable: true
    kwarg_only: true
    name: dtype
    type: c10::optional<ScalarType>
  - annotation: null
    default: c10::nullopt
    dynamic_type: Layout
    is_nullable: true
    kwarg_only: true
    name: layout
    type: c10::optional<Layout>
  - annotation: null
    default: c10::nullopt
    dynamic_type: Device
    is_nullable: true
    kwarg_only: true
    name: device
    type: c10::optional<Device>
  - annotation: null
    default: c10::nullopt
    dynamic_type: bool
    is_nullable: true
    kwarg_only: true
    name: pin_memory
    type: c10::optional<bool>
  method_of:
  - Type
  - namespace
  mode: native
  python_module: ''
  returns:
  - dynamic_type: Tensor
    name: result
    type: Tensor
  inplace: false
  is_factory_method: true
  abstract: false
  requires_tensor: false
  device_guard: true
  with_gil: false
  deprecated: false
```

-------------------

### build/aten/src/ATen/Functions.h
This file is used for out C++ API layer. Original definitions in this file should not change to keep providing easier to use API for C++ code and BC reasons. 

**Proposal:** 
- Add overloads for all functions that have TensorOptions with a version with expanded argument list instead. 

**Example:**
Original
`static inline Tensor bartlett_window(int64_t window_length, const TensorOptions & options={});`

```
static inline Tensor bartlett_window(int64_t window_length, const TensorOptions & options) {
#ifdef USE_STATIC_DISPATCH
    return TypeDefault::bartlett_window(window_length, options);
#else
    globalLegacyTypeDispatch().initForTensorTypeSet(options.type_set());
    static auto table = globalATenDispatch().getOpTable("aten::bartlett_window(int window_length, *, ScalarType? dtype=None, Layout? layout=None, Device? device=None, bool? pin_memory=None) -> Tensor");
    return table->getOp<Tensor (int64_t, const TensorOptions &)>(options.type_set())(window_length, options);
#endif
}

```

Proposed
```
static inline Tensor bartlett_window(int64_t window_length, const TensorOptions & options={});
static inline Tensor _bartlett_window(int64_t window_length, c10::optional<ScalarType> dtype, c10::optional<Layout> layout, c10::optional<Device> device, c10::optional<bool> pin_memory);

static inline Tensor _bartlett_window(int64_t window_length, c10::optional<ScalarType> dtype, c10::optional<Layout> layout, c10::optional<Device> device, c10::optional<bool> pin_memory) {

auto options = TensorOptions(dtype, layout, device, pin_memory);

#ifdef USE_STATIC_DISPATCH
    return TypeDefault::bartlett_window(window_length, options);
#else
    globalLegacyTypeDispatch().initForTensorTypeSet(options.type_set());
    static auto table = globalATenDispatch().getOpTable("aten::bartlett_window(int window_length, *, ScalarType? dtype=None, Layout? layout=None, Device? device=None, bool? pin_memory=None) -> Tensor");
    return table->getOp<Tensor (int64_t, const TensorOptions &)>(options.type_set())(window_length, options);
#endif
}
```

-------------------
### build/aten/src/ATen/NativeFunctions.h

Original
`CAFFE2_API Tensor bartlett_window(int64_t window_length, const TensorOptions & options={});`

Proposed
`CAFFE2_API Tensor bartlett_window(int64_t window_length, c10::optional<ScalarType> dtype, c10::optional<Layout> layout, c10::optional<Device> device, c10::optional<bool> pin_memory);`

-------------------
### build/aten/src/ATen/TypeDefault.h

Original
`static Tensor bartlett_window(int64_t window_length, const TensorOptions & options);`

Proposed
`static Tensor _bartlett_window(int64_t window_length, c10::optional<ScalarType> dtype, c10::optional<Layout> layout, c10::optional<Device> device, c10::optional<bool> pin_memory);`

-------------------
### python_torch_functions_dispatch.h

Original
```
inline Tensor dispatch_bartlett_window(int64_t window_length, const TensorOptions & options) {
  torch::utils::maybe_initialize_cuda(options);
  AutoNoGIL no_gil;
  return torch::bartlett_window(window_length, options);
}
```

Proposed
```
inline Tensor dispatch_bartlett_window(int64_t window_length, c10::optional<ScalarType> dtype, c10::optional<Layout> layout, c10::optional<Device> device, c10::optional<bool> pin_memory) {
  torch::utils::maybe_initialize_cuda(device);
  AutoNoGIL no_gil;
  return torch::_bartlett_window(window_length, dtype, layout, device, pin_memory);
}
```

-------------------
### python_torch_functions.cpp

Original
```
static PyObject * THPVariable_bartlett_window(PyObject* self_, PyObject* args, PyObject* kwargs)
{
  HANDLE_TH_ERRORS
  static PythonArgParser parser({
    "bartlett_window(int64_t window_length, *, ScalarType dtype=None, Layout layout=torch.strided, Device device=None, bool pin_memory=False, bool requires_grad=False)",
    "bartlett_window(int64_t window_length, bool periodic, *, ScalarType dtype=None, Layout layout=torch.strided, Device device=None, bool pin_memory=False, bool requires_grad=False)",
  }, /*traceable=*/true);

  ParsedArgs<8> parsed_args;
  auto r = parser.parse(args, kwargs, parsed_args);

  if (r.idx == 0) {
    auto window_length = r.toInt64(0);
    auto dtype = r.scalartype(1);
    auto device = r.device(3);
    const auto options = TensorOptions()
        .dtype(dtype)
        .device(device)
        .layout(r.layout(2).layout)
        .requires_grad(r.toBool(5))
        .pinned_memory(r.toBool(4));
    return wrap(dispatch_bartlett_window(window_length, options));
  } else if (r.idx == 1) {
    auto window_length = r.toInt64(0);
    auto periodic = r.toBool(1);
    auto dtype = r.scalartype(2);
    auto device = r.device(4);
    const auto options = TensorOptions()
        .dtype(dtype)
        .device(device)
        .layout(r.layout(3).layout)
        .requires_grad(r.toBool(6))
        .pinned_memory(r.toBool(5));
    return wrap(dispatch_bartlett_window(window_length, periodic, options));
  }
  Py_RETURN_NONE;
  END_HANDLE_TH_ERRORS
}
```

Proposed
```
static PyObject * THPVariable_bartlett_window(PyObject* self_, PyObject* args, PyObject* kwargs)
{
  HANDLE_TH_ERRORS
  static PythonArgParser parser({
    "bartlett_window(int64_t window_length, *, ScalarType dtype=None, Layout layout=torch.strided, Device device=None, bool pin_memory=False, bool requires_grad=False)",
    "bartlett_window(int64_t window_length, bool periodic, *, ScalarType dtype=None, Layout layout=torch.strided, Device device=None, bool pin_memory=False, bool requires_grad=False)",
  }, /*traceable=*/true);

  ParsedArgs<8> parsed_args;
  auto r = parser.parse(args, kwargs, parsed_args);

  if (r.idx == 0) {
    auto window_length = r.toInt64(0);
    auto dtype = r.scalartype(1);
    auto layout = r.layout(2).layout;
    auto device = r.device(3);
    auto pin_memory = r.toBool(4);
    auto requires_grad = r.toBool(5);

    return wrap(dispatch__bartlett_window(window_length, dtype, layout, device, pin_memory, requires_grad));
  } else if (r.idx == 1) {
    auto window_length = r.toInt64(0);
    auto periodic = r.toBool(1);
    auto dtype = r.scalartype(2);
    auto layout = r.layout(3).layout;
    auto device = r.device(4);
    auto pin_memory = r.toBool(5);
    auto requires_grad = r.toBool(6);

    return wrap(dispatch__bartlett_window(window_length, periodic, dtype, layout, device, pin_memory, requires_grad));
  }
  Py_RETURN_NONE;
  END_HANDLE_TH_ERRORS
}
```

-------------------
### variable_factories.h
Changes here are not very obvious. We need to figure out if we can just pass all the inputs to jit one by one instead of options object. Also, requires_grad value is not being passed in the current proposal.

Original:
```
inline at::Tensor bartlett_window(int64_t window_length, const at::TensorOptions & options = {}) {
  torch::jit::Node* node = nullptr;
  std::shared_ptr<jit::tracer::TracingState> tracer_state;
  if (jit::tracer::isTracing()) {
    tracer_state = jit::tracer::getTracingState();
    at::Symbol op_name;
    op_name = jit::Symbol::fromQualString("aten::bartlett_window");
    node = tracer_state->graph->create(op_name, /*num_outputs=*/0);
    jit::tracer::recordSourceLocation(node);
    jit::tracer::addInputs(node, "window_length", window_length);
    jit::tracer::addInputs(node, "options", options);
    tracer_state->graph->insertNode(node);
  
    jit::tracer::setTracingState(nullptr);
  }
  at::Tensor tensor = ([&]() {
    at::AutoNonVariableTypeMode non_var_type_mode(true);
    return at::bartlett_window(window_length, at::TensorOptions(options).is_variable(false));
  })();
  at::Tensor result =
    autograd::make_variable(std::move(tensor), /*requires_grad=*/options.requires_grad());
  if (tracer_state) {
    jit::tracer::setTracingState(std::move(tracer_state));
    jit::tracer::addOutput(node, result);
  }
  return result;
}
```

Proposed:
```
inline at::Tensor bartlett_window(int64_t window_length, c10::optional<ScalarType> dtype, c10::optional<Layout> layout, c10::optional<Device> device, c10::optional<bool> pin_memory) {
  torch::jit::Node* node = nullptr;
  std::shared_ptr<jit::tracer::TracingState> tracer_state;
  if (jit::tracer::isTracing()) {
    tracer_state = jit::tracer::getTracingState();
    at::Symbol op_name;
    op_name = jit::Symbol::fromQualString("aten::bartlett_window");
    node = tracer_state->graph->create(op_name, /*num_outputs=*/0);
    jit::tracer::recordSourceLocation(node);
    jit::tracer::addInputs(node, "window_length", window_length);
    jit::tracer::addInputs(node, "dtype", dtype);
    jit::tracer::addInputs(node, "layout", layout);
    jit::tracer::addInputs(node, "device", device);
    jit::tracer::addInputs(node, "pin_memory", pin_memory);
    tracer_state->graph->insertNode(node);
  
    jit::tracer::setTracingState(nullptr);
  }
  at::Tensor tensor = ([&]() {
    at::AutoNonVariableTypeMode non_var_type_mode(true);
    return at::_bartlett_window(window_length, dtype, layout, device, pin_memory);
  })();
  at::Tensor result =
    autograd::make_variable(std::move(tensor), false);
  if (tracer_state) {
    jit::tracer::setTracingState(std::move(tracer_state));
    jit::tracer::addOutput(node, result);
  }
  return result;
}
```

-------------------
### VariableType_0.cpp

Original
```
Tensor VariableType::bartlett_window(int64_t window_length, const TensorOptions & options) {
  RECORD_FUNCTION("bartlett_window", std::vector<c10::IValue>({}), Node::peek_at_next_sequence_nr());
  torch::jit::Node* node = nullptr;
  std::shared_ptr<jit::tracer::TracingState> tracer_state;
  if (jit::tracer::isTracing()) {
    tracer_state = jit::tracer::getTracingState();
    at::Symbol op_name;
    op_name = jit::Symbol::fromQualString("aten::bartlett_window");
    node = tracer_state->graph->create(op_name, /*num_outputs=*/0);
    jit::tracer::recordSourceLocation(node);
    jit::tracer::addInputs(node, "window_length", window_length);
    jit::tracer::addInputs(node, "options", options);
    tracer_state->graph->insertNode(node);
  
    jit::tracer::setTracingState(nullptr);
  }
  auto result = TypeDefault::bartlett_window(window_length, options);
  if (tracer_state) {
    jit::tracer::setTracingState(std::move(tracer_state));
    jit::tracer::addOutput(node, result);
  }
  return result;
}
```

Proposed
```
Tensor VariableType::bartlett_window(int64_t window_length, c10::optional<ScalarType> dtype, c10::optional<Layout> layout, c10::optional<Device> device, c10::optional<bool> pin_memory) {
RECORD_FUNCTION("bartlett_window", std::vector<c10::IValue>({}), Node::peek_at_next_sequence_nr());
  torch::jit::Node* node = nullptr;
  std::shared_ptr<jit::tracer::TracingState> tracer_state;
  if (jit::tracer::isTracing()) {
    tracer_state = jit::tracer::getTracingState();
    at::Symbol op_name;
    op_name = jit::Symbol::fromQualString("aten::_bartlett_window");
    node = tracer_state->graph->create(op_name, /*num_outputs=*/0);
    jit::tracer::recordSourceLocation(node);
    jit::tracer::addInputs(node, "window_length", window_length);
    jit::tracer::addInputs(node, "dtype", dtype);
    jit::tracer::addInputs(node, "layout", layout);
    jit::tracer::addInputs(node, "device", device);
    jit::tracer::addInputs(node, "pin_memory", pin_memory);
    tracer_state->graph->insertNode(node);
  
    jit::tracer::setTracingState(nullptr);
  }
  auto result = TypeDefault::_bartlett_window(window_length, dtype, layout, device, pin_memory);
  if (tracer_state) {
    jit::tracer::setTracingState(std::move(tracer_state));
    jit::tracer::addOutput(node, result);
  }
  return result;
}
```

-------------------
### VariableType.h
Original:
`static Tensor VariableType::bartlett_window(int64_t window_length, const TensorOptions & options)`

Proposed: 
`static Tensor bartlett_window(int64_t window_length, c10::optional<ScalarType> dtype, c10::optional<Layout> layout, c10::optional<Device> device, c10::optional<bool> pin_memory`

-------------------
### register_aten_ops_2.cpp

Original:
```
Operator(
         "aten::bartlett_window(int window_length, *, ScalarType? dtype=None, Layout? layout=None, Device? device=None, bool? pin_memory=None) -> Tensor",
         [](Stack & stack) {
         
             const auto options = TensorOptions()
                     .dtype((std::move(peek(stack, 1, 5))).toOptional<ScalarType>())
                     .layout((std::move(peek(stack, 2, 5))).toOptional<c10::Layout>())
                     .device((std::move(peek(stack, 3, 5))).toOptional<c10::Device>())
                     .pinned_memory((std::move(peek(stack, 4, 5))).toOptional<bool>());
             #ifdef USE_STATIC_DISPATCH
                 auto result_ = at::bartlett_window((std::move(peek(stack, 0, 5))).toInt(),
             options);
             #else
                 auto result_ = torch::bartlett_window((std::move(peek(stack, 0, 5))).toInt(),
             options);
             #endif
             drop(stack, 5);
             pack(stack, std::move(result_));
             return 0;
         },
         atenOperatorOptions()
     ),
```

Proposed:
```
Operator(
         "aten::bartlett_window(int window_length, *, ScalarType? dtype=None, Layout? layout=None, Device? device=None, bool? pin_memory=None) -> Tensor",
         [](Stack & stack) {
         
             #ifdef USE_STATIC_DISPATCH
                 auto result_ = at::bartlett_window((std::move(peek(stack, 0, 5))).toInt(),
             std::move(peek(stack, 1, 5))).toOptional<ScalarType>(), std::move(peek(stack, 2, 5))).toOptional<c10::Layout>(), (std::move(peek(stack, 3, 5))).toOptional<c10::Device>(), (std::move(peek(stack, 4, 5))).toOptional<bool>());
             #else
                 auto result_ = torch::bartlett_window((std::move(peek(stack, 0, 5))).toInt(),
             std::move(peek(stack, 1, 5))).toOptional<ScalarType>(), std::move(peek(stack, 2, 5))).toOptional<c10::Layout>(), (std::move(peek(stack, 3, 5))).toOptional<c10::Device>(), (std::move(peek(stack, 4, 5))).toOptional<bool>());
             #endif
             drop(stack, 5);
             pack(stack, std::move(result_));
             return 0;
         },
         atenOperatorOptions()
     ),
```
