### ISSUE TITLE
[RFC] Target Specifier for CI on Pull Requests

### ISSUE THREAD

**Issue by seemethere** [pytorch/pytorch#35975]
## 🚀 Feature

There should be a way to specify which jobs get run on PRs without having to edit the `.circleci/config.yml`.

## Motivation

The current way to test jobs that don't run normally on pull requests is to create a *TEST* commit that edits the contents of the `.circleci/config.yml`. This becomes problematic because it's not very apparent how to do this and the CI results are lost as soon as you revert that commit in your pull request.

An example of a *TEST* commit: https://github.com/pytorch/pytorch/pull/35907/commits/ee54fbcd83b16eb5c84172a89497aa7c85c8434b

## Pitch

We could edit the current `.circleci/config.yml` to utilize [pipeline parameters](https://circleci.com/docs/2.0/pipeline-variables/#pipeline-parameters-in-configuration) and remote [job triggering](https://circleci.com/docs/api/v2/#trigger-a-new-pipeline) in order to create a target specifier within our PRs that could tell downstream jobs how to trigger.

### How would this be executed?

Pipeline parameters will be specified at the top level indicating different categories of jobs that can potentially run.

Users will then label their PR's with specific CI labels that will be mapped to CircleCI pipeline parameters in a configuration file at `.github/pytorch-circleci-labels.yml`.

The bot will pick up this labeling event and [trigger a new CircleCI workflow](https://circleci.com/docs/api/v2/#trigger-a-new-pipeline) with the pipeline parameter set to `true`.

**NOTE**: For branches that are not pull requests, all specifiers will be turned to `true` *(not yet implemented)*

**NOTE**: There is a limitation within the CircleCI API v2 that does not allow users to trigger new workflows with parameters for pull requests that originate from forks. See [CCI-I-1280](https://ideas.circleci.com/ideas/CCI-I-1280)

### An example

Example configuration: (`.github/pytorch-circleci-labels.yml`)
```yaml
labels_to_circle_params:
  ci/binaries: run_binaries_tests
  ci/bleh: run_bleh_tests
  ci/foo: run_foo_tests
```

The label `ci/binaries` is applied to a PR and the bot automatically triggers a new workflow to run with `run_binaries_tests` set to true using the [CircleCI API workflow endpoint](https://circleci.com/docs/api/v2/#trigger-a-new-pipeline)

### Some potential shortfalls

Discovery of this feature will still be an issue as it might not be apparent how to actually use the specifiers, but that could be overcome with a message from the bot on how use the specifiers.

Maintenance of this ouside of the autogenerated portions of the `config.yml` might prove to be hard to maintain the specifiers, so we should discuss on how those jobs could be easier to maintain.

## Alternatives

Previous attempts to do this include the `should-run.sh` script which has been removed but achieved a similar idea.

## Additional context

A working example of the remote job triggering along with pipeline parameters can be found here: https://github.com/seemethere/test-repo/tree/test_docker_build

cc @ezyang @seemethere, @malfet, @kostmo

**Comment by suo** [comment]
Nice! I definitely think this is an improvement on `should-run.sh` and co. One use case to keep in mind—I might want to trigger tests as a reviewer, not a committer. For example, OSS contributors or new team members are unlikely to know about these specifiers, and being able to trigger them as a reviewer would help with the discoverability issue.

One way to solve this: in addition to the `specifier` workflow, we also have a GH action that searches through comments on PRs and triggers jobs based on the same specifiers. So I could comment on the PR with `@pytorchbot [ci-binary]` or something and have it trigger additional jobs.

**Comment by ezyang** [comment]
Another downside (which I think is worth it, but worth calling out) is that you increase the latency, since you first trigger a workflow to compute what rpcs to do, and then that triggers *another* workflow which actually does the work.

**Comment by seemethere** [comment]
I think that a better approach to appease both the labeling and latency is to create this as a github action that then triggers downstream circleci workflows.

Basically:
1. Use pushes a commit
2. All circleci workflows off by default
3. Github action analyzes the PR and kicks off circleci workflows with parameters that are based on the currently applied labels.

This affords us flexibility as it makes it explicit where the kick off is happening. It also allows us to create categories so that labels can be applied that apply to multiple downstream parameters.

**Comment by ezyang** [comment]
For other readers: we also have to manually manage cancelling jobs when people push updates.

**Comment by seemethere** [comment]
So I just realized this with github actions that users without write access or users who submit pull requests from forks won't be able to access secret like a circleci token that's used to trigger a workflow.

This will probably mean that this won't be able to be configured as a github action and might need to be configured as a github app instead.

@suo or @ezyang how did we approach this in the past? I noticed that there's issues with https://github.com/pytorch/add-annotations-github-action accessing the GITHUB_TOKEN which leads me to believe that there's really no way for this to be a github action at all.

https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

**Comment by ezyang** [comment]
@seemethere in CircleCI we just make "secrets" (such as the keys for accessing sccache) available to all pull requests (so it's not very secret, but you do have to write a naughty update to the CI scripts to actually exfiltrate the secret).

**Comment by seemethere** [comment]
@ezyang It's not the CircleCI portion of it that I'm worried about, it's on the Github Actions side where we cannot share credentials with people who are submitting PRs from forks.

Which basically means anyone submitting a PR from a fork wouldn't be able to use the CIRCLECI_TOKEN that we'd need to have in order to trigger downstream workflows.

**Comment by ezyang** [comment]
I guess what I'm saying is, you are going to need some way of getting at the token from public CI. CircleCI provides some way to do it, but it's not true security, it's security by obscurity, but it is better than just publishing the token directly in our repository. If GH actions has no way of doing it, you'll need to figure out some place to put the key that is not too obvious to extract out, but can still be used by users. Or I guess you can just check it into the repo (this is a bad idea with AWS keys as AWS will revoke your keys if it finds them on the public net, but maybe CircleCI doesn't do this.)

**Comment by seemethere** [comment]
Had a chat with @ezyang today and we're going to proceed with deploying this functionality as added features on top of [pytorch/pytorch-probot](https://github.com/pytorch/pytorch-probot).

**Comment by seemethere** [comment]
Hey so one little wrinkle that I hadn't considered is how the target specifier works on pushes.

Pushes would be broken if we started to split things up and gate them through target specification.

## Problem overview and context
This thought came about when I was considering how to implement the target specification for the binary workflow we have setup for release builds here in this repository.

First and foremost the central idea behind it being that the new binary build workflow would need to be gated on a singular pipeline variable, most likely named `ci/binaries`.

Right now the binary jobs are gated on filter branches which would have to be removed if we wanted to use them with the target specifier to run on pull requests.

This new filter branch would look similar to:
```diff
          filters:
            branches:
-              only: nightly
+              only: *
            tags:
              only: /v[0-9]+(\.[0-9]+)*-rc[0-9]+/

```

So the big issue becomes, when the workflow is split out and is now gated by a pipeline variable, how do we ensure that the workflow is actually run by default on the correct branches that we wanted to run it on.

> Note solutions are ordered from perceived implementation complexity

## Solution 1 (Run everything on `push` for specific branches)

For this we would basically take all parameters from our config and set them to true and then kick off CircleCI builds for specific branches that could be outline in configuration like:

<details>
<summary> .github/pytorch-circleci-labels.yml </summary>

```yaml
run_all_on:
  branches:
    - master
    - nightly
    - release/*
  tags:
    - /v[0-9]+(\.[0-9]+)*-rc[0-9]+/
```

</details>

This solution has its obvious downsides, one being that there are workflows that we don't run (like the full binary builds) on every push because doing so would be costly.

## Solution 2 (Choose which parameters to set true on specific branches)

With this one we can set specific parameters to be set to true on branches / tags that we choose

This can be achieved by adding a separate field to our configuration that

<details>
<summary> .github/pytorch-circleci-labels.yml </summary>

```yaml
labels_to_circle_params:
  ci/binaries: 
    parameter: run_binaries_workflow
    default_true_on:
      branches:
        - nightly
      tags:
        - /v[0-9]+(\.[0-9]+)*-rc[0-9]+/
```

</details>

## Solution 3 (Split everything into two separate workflows, one for PRs, one for everything else)

This last solution adds a lot of complexity to our `.circleci/config.yml` by basically declaring two workflows for jobs we only want to run on specific branches and jobs we want the target specifier to run through. This would look somewhat similarly to this:

<details>
<summary> .circleci/config.yml </summary>

```yaml
workflows:
  binaries_prs:
    when: << pipeline.variables.run_binaries_workflow >>
    jobs:
      - binary_linux_build:
          name: binary_linux_manywheel_3_6m_cpu_devtoolset7_nightly_build
          build_environment: "manywheel 3.6m cpu devtoolset7"
          requires:
            - setup
          filters:
            branches:
              only: .*
          docker_image: "pytorch/manylinux-cuda102"
  binaries_branches:
    jobs:
      - binary_linux_build:
          name: binary_linux_manywheel_3_6m_cpu_devtoolset7_nightly_build
          build_environment: "manywheel 3.6m cpu devtoolset7"
          requires:
            - setup
          filters:
            branches:
              only:
                - nightly
            tags:
                - /v[0-9]+(\.[0-9]+)*-rc[0-9]+/
          docker_image: "pytorch/manylinux-cuda102"
```

</details>
