### ISSUE TITLE
The defintion of the job `binary_windows_upload` in config.yml is broken

### ISSUE THREAD

**Issue by peterjc123** [pytorch/pytorch#40786]
## 🐛 Bug

Per title.

```yml
  binary_windows_upload:
    <<: *binary_windows_params
    parameters:
      build_environment:
        type: string
        default: ""
      executor:
        type: string
        default: "windows-medium-cpu-with-nvidia-cuda"
    executor: <<parameters.executor>>
    docker:
      - image: continuumio/miniconda
    steps:
    # See Note [Workspace for CircleCI scripts] in job-specs-setup.yml
    - checkout
    - attach_workspace:
        at: /root/workspace
    - run:
        <<: *binary_checkout
    - run:
        <<: *binary_populate_env
    - run:
        name: Upload
        no_output_timeout: "10m"
        command: |
          set -eux -o pipefail
          script="/pytorch/.circleci/scripts/binary_windows_upload.sh"
          cat "$script"
          source "$script"
```

The `executor` and `docker` key are exclusive in a job definition.
