### ISSUE TITLE
pytorch_android_gradle_custom_build_single is still hardcoded to 09062ef-ab58-422a-b295-36c4eed6e906

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#43338]
```
  pytorch_android_gradle_custom_build_single:
    environment:
      BUILD_ENVIRONMENT: pytorch-linux-xenial-py3-clang5-android-ndk-r19c-gradle-custom-build-single
      DOCKER_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3-clang5-android-ndk-r19c:209062ef-ab58-422a-b295-36c4eed6e906"
      PYTHON_VERSION: "3.6"
    resource_class: large
    machine:
      image: ubuntu-1604:201903-01
```

This means it's not getting updates.

cc @ezyang @seemethere
