### ISSUE TITLE
commit_sha no longer being passed to add-annotations-github-action

### ISSUE THREAD

**Issue by samestep** [pytorch/pytorch#53833]
Since #53719, the `commit_sha` input is no longer being passed to [pytorch/add-annotations-github-action](https://github.com/pytorch/add-annotations-github-action) for flake8-py3 or clang-tidy. Compare:

- [flake8-py3 run](https://github.com/pytorch/pytorch/runs/2087587975) on `master` before #53719
  ```
  Run pytorch/add-annotations-github-action@master
  with:
    check_name: flake8-py3
    linter_output_path: flake8-output.txt
    commit_sha: f364e492dfb287e4043d37fffa1bcef55e2ac5dd
    regex: ^(?<filename>.*?):(?<lineNumber>\d+):(?<columnNumber>\d+): (?<errorCode>\w+\d+) (?<errorDesc>.*)
  ```
- [flake8-py3 run](https://github.com/pytorch/pytorch/runs/2087796245) on `master` after #53719
  ```
  Run pytorch/add-annotations-github-action@master
  with:
    check_name: flake8-py3
    linter_output_path: flake8-output.txt
    regex: ^(?<filename>.*?):(?<lineNumber>\d+):(?<columnNumber>\d+): (?<errorCode>\w+\d+) (?<errorDesc>.*)
  ```

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra
