### ISSUE TITLE
[rfc] Hardcoded Target Determination

### ISSUE THREAD

**Issue by driazati** [pytorch/pytorch#63781]
Target determination is very difficult to do correctly. Internally, FB relies on a graph of Buck dependencies which has been built over time to extract information on how to schedule tests for a particular diff. In OSS PyTorch, we don’t have this information on a meaningful scale. We have a Bazel build that is structured very similarly, but the targets that it defines are not granular enough to get some of the things we need (e.g. going from C++ → Python, all the code is bottlenecked through a small set of targets, so it’s difficult to say “for this Python code, this is the C++ code I need to test”).

In spite of this, there are some easy wins for target determination we can get, most notably for documentation only changes. These don’t need to run the tests (except in some small cases where [doctest](https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html) is used). We could manually encode these dependencies, and allow other teams to opt-in so that they can have faster build times as long as they stay within the walls of their codebase. The downside would be that they should expect a higher rate of reverts in case their code broke some un-run test.

This could be done in a file `tests/manual_determinations.yaml` that would look something like

```
rules:
  - name: FX team
    sources:
      # Globs are supported (using Python's fnmatch)
      - torch/quantization/fx/*
      - torch/fx/*
      - torch/include/torch/csrc/fx/*
      - torch/csrc/fx/*
      # Specific files can be referenced too
      - docs/source/fx.rst
   tests:
      - test/test_fx.py
 - name: Documentation changes
    sources:
      - docs/*
      - *.rst
      - *.md
    tests: []
```

If a PR only touches files in a `sources` or `tests` entry for a single rule, then only those tests will be run by `run_test.py`.

## Other options

* Run tests by pytest-like test filter (regex on test name) rather than file
* ???

cc @pytorch/pytorch-dev-infra
