### ISSUE TITLE
Incorrect reference to previous kernel in the warning displayed when overriding a previously registered kernel for the same operator and the same dispatch

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#65825]
Context:
For `mul.Tensor`, when I register a fallthrough impl for ZeroTensor key as well as a specific registration in native_functions.yaml, I get a runtime warning that my previously registered kernel is being overrided  for the same operator and the same dispatch key (as expected). However, the previous_kernel, it points to seems incorrect. 

Relevant changes:
```
--- a/aten/src/ATen/ZeroTensorFallback.cpp
+++ b/aten/src/ATen/ZeroTensorFallback.cpp
@@ -88,8 +88,8 @@ namespace at {
-    // m.impl("mul.Tensor", torch::CppFunction::makeFallthrough());
+    m.impl("mul.Tensor", torch::CppFunction::makeFallthrough());
```

`aten/src/ATen/native/native_functions.yaml`
```
- func: mul.Tensor(Tensor self, Tensor other) -> Tensor
  device_check: NoCheck   # TensorIterator
  structured_delegate: mul.out
  variants: function, method
  dispatch:
    SparseCPU, SparseCUDA: mul_sparse
    MkldnnCPU: mkldnn_mul
    ZeroTensor: mul_zerotensor
```

PR:
https://github.com/pytorch/pytorch/pull/64837

```python
import torch
x=torch.efficientzerotensor(2)
y=torch.randn(2)
z=torch.mul(x, y)
print(z, z.is_zerotensor())
```

output:
```
[W OperatorEntry.cpp:129] Warning: Overriding a previously registered kernel for the same operator and the same dispatch key
  operator: aten::add.Tensor(Tensor self, Tensor other, *, Scalar alpha=1) -> (Tensor)
    registered at aten/src/ATen/RegisterSchema.cpp:20
  dispatch key: ZeroTensor
  previous kernel: registered at ../aten/src/ATen/BatchingRegistrations.cpp:1020
       new kernel: registered at aten/src/ATen/RegisterZeroTensor.cpp:89 (function registerKernel)
[W OperatorEntry.cpp:129] Warning: Overriding a previously registered kernel for the same operator and the same dispatch key
  operator: aten::mul.Tensor(Tensor self, Tensor other) -> (Tensor)
    registered at aten/src/ATen/RegisterSchema.cpp:20
  dispatch key: ZeroTensor
  previous kernel: registered at ../aten/src/ATen/BatchingRegistrations.cpp:1020
       new kernel: registered at aten/src/ATen/RegisterZeroTensor.cpp:89 (function registerKernel)
Entering mul_zerotensor
tensor([0., 0.]) True
```
