### ISSUE TITLE
AtenLtcTsTensorTest.TestAmpForeachNonFiniteCheckAndUnscale, @desertfire

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#68878]
Running `XLA_TEST_DUMP_TENSORS=1 test/cpp/build/test_ptltc --gtest_filter=AtenLtcTsTensorTest.TestAmpForeachNonFiniteCheckAndUnscale` gives the following error,
```
[ CPUFloatType{4} ]
Compared Tensors:
 0.2000
 0.4000
 0.6000
 0.8000
[ CPUFloatType{4} ]
-vs-
 1
 2
 3
 4
[ CPUFloatType{4} ]
```

Based on its signature in native_functions.yaml, it looks like the in-place update did not happen when an op is not supported by LT (meaning the op goes through the fallback path).
```
- func: _amp_foreach_non_finite_check_and_unscale_(Tensor(a!)[] self, Tensor(b!) found_inf, Tensor inv_scale) -> ()
  variants: function
  dispatch:
    CUDA: _amp_foreach_non_finite_check_and_unscale_cuda_
```
