### ISSUE TITLE
Structured Kernel Precompute codegen should handle fields that don't replace anything

### ISSUE THREAD

**Issue by bdhirsh** [pytorch/pytorch#71314]
Structured kernels have some codegen logic that allows you to "precompute" some fields in the meta function, that can be used directly in the impl function. The syntax for this in native_functions.yaml looks like this:

```
- func: avg_pool2d.out(Tensor self, int[2] kernel_size, int[2] stride=[], int[2] padding=0, bool ceil_
  python_module: nn
  structured: True
  precomputed:
  - kernel_size -> int kH, int kW
  - stride -> int dH, int dW
  - padding -> int padH, int padW
  dispatch:
    CPU: avg_pool2d_out_cpu
    CUDA: avg_pool2d_out_cuda
    MkldnnCPU: mkldnn_avg_pool2d_out
```

Notice that there's a `precomputed` section in the yaml, specifying which arguments should be replaced with precomputed fields. In the above example, `kernel_size` is replaced with `kH` and `kW`.

This has been great for most use cases, but some times it might be useful to precompute some values **without** replacing the values that they came from. For example, in `fractional_max_pool3d`, we'd like to compute the values `int64_t numBatch, int64_t inputT, int64_t inputH, int64_t inputW` from `self`, but we don't want to replace `self` (we still want to pass it into the impl function).

You could imagine hacking around this by writing replacements like `self -> Tensor self_, int64_t numBatch, int64_t inputT, int64_t inputH, int64_t inputW`. But that's not really what we want - we want to retain `self`, and generate some extra precomputed values from it.

**yaml syntax**
A potential syntax in the yaml could look something like this:
```
  precomputed:
  - numBatch, inputT, inputH, inputW
  - kernel_size -> int kH, int kW
  - stride -> int dH, int dW
  - padding -> int padH, int padW
```
Where we expect + enforce that the first line (optionally) doesn't have an arrow, indicating that it won't replace any values and it will only add new values.

If we land this, then we should test it out by precomputing extra values in `fractional_max_pool3d`. See the [comments](https://github.com/pytorch/pytorch/pull/70414#issuecomment-1012585829) where this initially came up.

cc @ezyang @bhosmer @bdhirsh
