### ISSUE TITLE
aten::batch_norm schema does not mention mutation of running_mean/running_var

### ISSUE THREAD

**Issue by silvasean** [pytorch/pytorch#73050]
### 🐛 Describe the bug

aten::batch_norm's schema has the following arguments:

```
  arguments:
    arg: {'name': 'input', 'type': 'Tensor', 'pytype': 'Tensor'}
    arg: {'name': 'weight', 'type': 'Tensor?', 'pytype': 'Optional[Tensor]'}
    arg: {'name': 'bias', 'type': 'Tensor?', 'pytype': 'Optional[Tensor]'}
    arg: {'name': 'running_mean', 'type': 'Tensor?', 'pytype': 'Optional[Tensor]'}
    arg: {'name': 'running_var', 'type': 'Tensor?', 'pytype': 'Optional[Tensor]'}
    arg: {'name': 'training', 'type': 'bool', 'pytype': 'bool'}
    arg: {'name': 'momentum', 'type': 'float', 'pytype': 'float'}
    arg: {'name': 'eps', 'type': 'float', 'pytype': 'float'}
    arg: {'name': 'cudnn_enabled', 'type': 'bool', 'pytype': 'bool'}
```

Note that `running_mean` and `running_var` don't have `alias_info`. This makes some sense, since aliases to them are not returned, so there is no need for "alias" info per se, but currently `alias_info` also is the structure that contains the `is_write` flag. This makes it hard for downstream to automatically understand the semantics of the op.

Context: In the [Torch-MLIR](https://github.com/llvm/torch-mlir) project, we [generate](https://github.com/llvm/torch-mlir/blob/ed9bd556b3f59feb0fe1cca9776a3c2eb82fe826/python/torch_mlir/dialects/torch/importer/jit_ir/build_tools/torch_ods_gen.py#L1) MLIR operation descriptions (called "ODS") for the operators in the JIT registry. We infer various information and annotate the MLIR operations based on the schema. Two such properties are:
- HasValueSemantics (i.e., is it purely functional). We currently use the absence of alias_info to indicate that, but that seems to be incorrect for aten::batch_norm, which is not purely functional
- ReadOnly (not yet implemented) - a weaker version of HasValueSemantics -- it may introduce aliases, but it is guaranteed not to mutate any operands. Suitable for view-like ops, list getitem, etc.

How can we correctly infer these properties from the registry?

@bdhirsh

### Versions

Currently working off nightly at the time of this bug report.
