### ISSUE TITLE
cpp-extensions strange behaviour during cusparse function call

### ISSUE THREAD

**Issue by Daulbaev** [pytorch/pytorch#7356]
I'm trying to use cpp-extensions with CUDA to convert csr matrix to csc matrix.

I've written the following function:
```
std::vector<at::Tensor> csr_to_csc_cuda(
at::Tensor A_data, 
at::Tensor A_indices, 
at::Tensor A_indptr, 
int n_cols) 
{
    auto state = at::globalContext().lazyInitCUDA();
    auto handle = THCState_getCurrentSparseHandle(state);
    int nnz = A_data.size(0);
    int m = A_indptr.size(0) - 1;
    auto B_data = at::infer_type(A_data).tensor({nnz}); 
    auto B_indptr = at::infer_type(A_indptr).tensor({nnz}); 
    auto B_indices = at::infer_type(A_indices).tensor({n_cols + 1}); 
    cusparseDcsr2csc(handle, m, n_cols, nnz, 
        A_data.data<double>(), 
        A_indptr.data<int>(), 
        A_indices.data<int>(), 
        B_data.data<double>(), 
        B_indptr.data<int>(), 
        B_indices.data<int>(), 
        CUSPARSE_ACTION_NUMERIC, 
        CUSPARSE_INDEX_BASE_ZERO);
    return {B_data, B_indptr, B_indices};
}
```

which simply calls cusparseDcsr2csc. I also Included all headers, added .cpp file with an interface an so on.
Then I built the whole project and there were no errors. But when I try to import this function Python raises a strange ImportError: /opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/dmg_cuda-0.0.0-py3.6-linux-x86_64.egg/dmg_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cusparseDcsr2csc

I am not sufficiently familiar with CUDA internal structure, but some people with the same problem simply added some more compilation flags to manage it. Could you tell me what's wrong?

P.S. I've also written cusparseDcsrmm2, and it works well (but the resulting array is stored in Fortran-style ordering).

**Comment by fmassa** [comment]
Can you try creating a cuda tensor and performing a bias/ sparse bias call before loading your lib in python?

**Comment by Daulbaev** [comment]
@fmassa Sorry, but what is a 'bias call'?

**Comment by fmassa** [comment]
Sorry, autocorrect here. I meant BLAS, like a matrix multiplication

**Comment by Daulbaev** [comment]
Yes, I've already called cusparseDcsrmm2 from <cusparse.h> in the same file and everything worked well.

**Comment by fmassa** [comment]
Not sure if I understand it properly, but you can maybe just transpose the resulting tensor? Not sure if transpose in sparse tensors is free though

**Comment by Daulbaev** [comment]
Yes, I can transpose, though this operation is quite expensive :( 

But my question for now why does Python says that cusparseDcsr2csc is undefined symbol? With a high probability it's my fault. However there is a small chance that some extra flags should be added during compilation.

**Comment by ezyang** [comment]
CC @goldsborough 

`cpp_extensions` has flags to let you pass additional compilation args, that may solve your problem.

```
    Args:
        name: The name of the extension to build. This MUST be the same as the
            name of the pybind11 module!
        sources: A list of relative or absolute paths to C++ source files.
        extra_cflags: optional list of compiler flags to forward to the build.
        extra_cuda_cflags: optional list of compiler flags to forward to nvcc
            when building CUDA sources.
        extra_ldflags: optional list of linker flags to forward to the build.
        extra_include_paths: optional list of include directories to forward
            to the build.
        build_directory: optional path to use as build workspace.
        verbose: If ``True``, turns on verbose logging of load steps.
```
