### ISSUE TITLE
Codgen multiple derivatives from derivatives.yaml

### ISSUE THREAD

**Issue by drisspg** [pytorch/pytorch#79046]
Currently derivatives.yaml codegens one derivative formula that gets registered for all autograd dispatch keys.  There are some functions like `reshape_alias` defined below.
```yaml
- name: _reshape_alias(Tensor(a) self, int[] size, int[] stride) -> Tensor(a)
  self: grad.reshape(self.sizes())
  result: auto_linear
```
If NestedTensor was implemented for this function the backwards would fail because NestedTensor.size() is not implemented. 

### Workaround:
One could define the function in: `torch/csrc/autograd/VariableTypeManual.cpp` and register it with:
`TORCH_LIBRARY_IMPL(aten, Autograd*****, m)`

### Goal
The goal of this issue would be to define an extended schema to derivatives.yaml in order for multiple derivative implementations to be registered to different autograd dispatch keys.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7
