### ISSUE TITLE
Logging tensor may not log some kwargs as well as it should

### ISSUE THREAD

**Issue by Lezcano** [pytorch/pytorch#80343]
### 🐛 Describe the bug

In https://github.com/pytorch/pytorch/pull/80334 some tests started failing. See https://github.com/pytorch/pytorch/runs/7072209713?check_suite_focus=true
After trying to modify this test to use another function, I went on and tried `topk`. I wrote:
```python
log_input("x", x)
torch.ops.aten.topk(x, 1)
torch.ops.aten.topk(x, 1, 0)
torch.ops.aten.topk(x, 1, sorted=False)
torch.ops.aten.topk(x, 1, 0, sorted=False)
```
and the output was:
```
$0 = input('x')
$1, $2 = torch._ops.aten.topk.default($0, 1)
$3, $4 = torch._ops.aten.topk.default($0, 1, 0)
$5, $6 = torch._ops.aten.topk.default($0, 1, -1, True, False)
$7, $8 = torch._ops.aten.topk.default($0, 1, 0, True, False)
```
by the description of the test, it looks like this behaviour was not desired. wdyt? @ezyang 

### Versions

master

**Comment by ezyang** [comment]
topk has this signature:

```
- func: topk(Tensor self, int k, int dim=-1, bool largest=True, bool sorted=True) -> (Tensor values, Tensor indices)
  variants: method, function
  structured_delegate: topk.values
  dispatch:
    QuantizedCPU: topk_quantized_cpu
```

In particular, largest and sorted are accepted positionally. As such, they do not get recorded as kwargs. If we wanted them as kwargs we should have made them kwarg only.
