### ISSUE TITLE
PyTorch EC2 runners can not be used with standard actions

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#83986]
### 🐛 Describe the bug

I.e. even setup-python action fails, see
https://github.com/pytorch/torchdynamo/runs/7996989843?check_suite_focus=true

for following simple workflow file:
```
 test-inductor:
    runs-on: linux.4xlarge.nvidia.gpu
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8.13'
        cache: 'pip'
```

### Versions

CI

cc @seemethere @pytorch/pytorch-dev-infra
