### ISSUE TITLE
Document process of monitoring build pipeline

### ISSUE THREAD

**Issue by vladimir-aubrecht** [pytorch/pytorch#87693]
### Description
Document process of:

- Location of build pipeline [hud.pytorch.org](http://hud.pytorch.org/)
- Checks we perform for ensuring that pipeline is working.
- Steps which are necessary in order to fix the pipeline.

### Acceptance Criteria
- The documentation section of this comment is filled in with all the observations.

### Documentation
- TBD

**Comment by vladimir-aubrecht** [comment]
This is migrated ticket, originally posted by @Blackhex.

Example of CI job execution:

- The `periodic / win-vs2019-cuda11.7-py3 / test (default, 1, 2, windows.8xlarge.nvidia.gpu)` job is defined in `.github\workflows\periodic.yml:172`:
  ```
  win-vs2019-cuda11_7-py3-test:
    name: win-vs2019-cuda11.7-py3
    uses: ./.github/workflows/_win-test.yml
    needs: win-vs2019-cuda11_7-py3-build
    with:
      build-environment: win-vs2019-cuda11.7-py3
      cuda-version: "11.7"
      test-matrix: ${{ needs.win-vs2019-cuda11_7-py3-build.outputs.test-matrix }}
  ```
- `.github\workflows\_win-test.yml` sets the following env variables:
  ```
  USE_CUDA: 1
  INSTALL_WINDOWS_SDK: 1
  PYTHON_VERSION: 3.8
  PYTORCH_RETRY_TEST_CASES: 1
  PYTORCH_OVERRIDE_FLAKY_SIGNAL: 1
  VC_PRODUCT: "BuildTools"
  VC_VERSION: ""
  VS_VERSION: "16.8.6"
  VC_YEAR: "2019"
  AWS_DEFAULT_REGION: us-east-1
  PR_NUMBER: ${{ github.event.pull_request.number }}
  SHA1: ${{ github.event.pull_request.head.sha || github.sha }}
  CUDA_VERSION: 11.7
  PYTORCH_FINAL_PACKAGE_DIR: /c/${{ github.run_id }}/build-results/
  BUILD_ENVIRONMENT: win-vs2019-cuda11.7-py3
  ALPINE_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/tool/alpine"
  SHARD_NUMBER: ${{ matrix.shard }}
  NUM_TEST_SHARDS: ${{ matrix.num_shards }}
  TEST_CONFIG: ${{ matrix.config }}
  PR_BODY: ${{ github.event.pull_request.body }}
  TORCH_CUDA_ARCH_LIST: "7.0"
  ```
- `.github\workflows\_win-test.yml` executes `.jenkins/pytorch/win-test.sh`

**Comment by Blackhex** [comment]
### Documentation

The documentation on the related PyTorch process can be found in:

- [PyTorch Design Philosophy](https://pytorch.org/docs/master/community/design.html)
- [PyTorch Contribution Guide](https://pytorch.org/docs/master/community/contribution_guide.html)
- [PyTorch Governance | Mechanics](https://pytorch.org/docs/master/community/governance.html)
- [PyTorch Governance | Maintainers](https://pytorch.org/docs/master/community/persons_of_interest.html)
- [PyTorch Governance | Build + CI](https://pytorch.org/docs/master/community/build_ci_governance.html)
- [[EXTERNAL] PyTorch Maintainers Onboarding - Google Docs](https://docs.google.com/document/d/1-TvJCrCUQKqA5SymxtVF-Im1nrDhZXLsONe91zgs96o/edit)
- [[EXTERNAL] PyTorch CI Support Guidelines - Google Docs](https://docs.google.com/document/d/1Mxrjrs6kr7oBukmwSjG4LkfHpbAEw-bp2T-oxpzeDzg/edit)
- [[EXTERNAL] An Overview of PyTorch Governance - Google Slides](https://docs.google.com/presentation/d/1Z87zrGUT30AFdU-CAOHhGwgZpsNE8h2hgv1khgPhWP4/edit#slide=id.g147c4a1190e_0_848)

Example of CI job execution:

- The `periodic / win-vs2019-cuda11.7-py3 / test (default, 1, 2, windows.8xlarge.nvidia.gpu)` job is defined in `.github\workflows\periodic.yml:172`:
```
win-vs2019-cuda11_7-py3-test:
  name: win-vs2019-cuda11.7-py3
  uses: ./.github/workflows/_win-test.yml
  needs: win-vs2019-cuda11_7-py3-build
  with:
    build-environment: win-vs2019-cuda11.7-py3
    cuda-version: "11.7"
    test-matrix: ${{ needs.win-vs2019-cuda11_7-py3-build.outputs.test-matrix }}
```
- `.github\workflows\_win-test.yml` sets the following env variables:
```
USE_CUDA: 1
INSTALL_WINDOWS_SDK: 1
PYTHON_VERSION: 3.8
PYTORCH_RETRY_TEST_CASES: 1
PYTORCH_OVERRIDE_FLAKY_SIGNAL: 1
VC_PRODUCT: "BuildTools"
VC_VERSION: ""
VS_VERSION: "16.8.6"
VC_YEAR: "2019"
AWS_DEFAULT_REGION: us-east-1
PR_NUMBER: ${{ github.event.pull_request.number }}
SHA1: ${{ github.event.pull_request.head.sha || github.sha }}
CUDA_VERSION: 11.7
PYTORCH_FINAL_PACKAGE_DIR: /c/${{ github.run_id }}/build-results/
BUILD_ENVIRONMENT: win-vs2019-cuda11.7-py3
ALPINE_IMAGE: "308535385114.dkr.ecr.us-east-1.amazonaws.com/tool/alpine"
SHARD_NUMBER: ${{ matrix.shard }}
NUM_TEST_SHARDS: ${{ matrix.num_shards }}
TEST_CONFIG: ${{ matrix.config }}
PR_BODY: ${{ github.event.pull_request.body }}
TORCH_CUDA_ARCH_LIST: "7.0"
```
- `.github\workflows\_win-test.yml` executes `.jenkins/pytorch/win-test.sh`
