### ISSUE TITLE
[jit] gen_jit_dispatch generates duplicate "descriptor"s

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#9067]
Both following native tensor factory function entries generate same `descriptor` (`"bernoulli-5"`):
```yaml
- func: bernoulli(IntList size, Tensor p, *, TensorOptions options={}) -> Tensor
  variants: function

- func: bernoulli(IntList size, double p, *, TensorOptions options={}) -> Tensor
  variants: function
```

The corresponding `decl`s are
```py
{'abstract': False,
 'api_name': 'bernoulli',
 'args': ['size', 'p', 'options'],
 'arguments': [{'dynamic_type': 'IntList',
                'is_nullable': False,
                'name': 'size',
                'simple_type': 'IntList',
                'type': 'IntList'},
               {'dynamic_type': 'Tensor',
                'is_nullable': False,
                'name': 'p',
                'simple_type': 'Tensor',
                'type': 'const Tensor &'},
               {'default': 'static_cast<int64_t>(at::kFloat)',
                'name': 'dtype',
                'simple_type': 'int64_t'},
               {'default': '{static_cast<int64_t>(at::Device::Type::CPU), -1}',
                'name': 'device',
                'simple_type': 'IntList'},
               {'default': 'static_cast<int64_t>(at::kStrided)',
                'name': 'layout',
                'simple_type': 'int64_t'}],
 'base_name': 'bernoulli',
 'deprecated': False,
 'device_guard': True,
 'formals': ['IntList size',
             'const Tensor & p',
             'const TensorOptions & options'],
 'has_tensor_options': True,
 'inplace': False,
 'method_of': ['Type', 'namespace'],
 'method_prefix_derived': '',
 'mode': 'native',
 'name': 'bernoulli',
 'return_type': 'Tensor',
 'returns': [{'dynamic_type': 'Tensor', 'name': 'result', 'type': 'Tensor'}],
 'type_method_args': ['size', 'p', 'options'],
 'type_method_formals': ['IntList size',
                         'const Tensor & p',
                         'const TensorOptions & options'],
 'with_gil': False}
```
and 
```py
{'abstract': False,
 'api_name': 'bernoulli',
 'args': ['size', 'p', 'options'],
 'arguments': [{'dynamic_type': 'IntList',
                'is_nullable': False,
                'name': 'size',
                'simple_type': 'IntList',
                'type': 'IntList'},
               {'dynamic_type': 'double',
                'is_nullable': False,
                'name': 'p',
                'simple_type': 'double',
                'type': 'double'},
               {'default': 'static_cast<int64_t>(at::kFloat)',
                'name': 'dtype',
                'simple_type': 'int64_t'},
               {'default': '{static_cast<int64_t>(at::Device::Type::CPU), -1}',
                'name': 'device',
                'simple_type': 'IntList'},
               {'default': 'static_cast<int64_t>(at::kStrided)',
                'name': 'layout',
                'simple_type': 'int64_t'}],
 'base_name': 'bernoulli',
 'deprecated': False,
 'device_guard': True,
 'formals': ['IntList size', 'double p', 'const TensorOptions & options'],
 'has_tensor_options': True,
 'inplace': False,
 'method_of': ['Type', 'namespace'],
 'method_prefix_derived': '',
 'mode': 'native',
 'name': 'bernoulli',
 'return_type': 'Tensor',
 'returns': [{'dynamic_type': 'Tensor', 'name': 'result', 'type': 'Tensor'}],
 'type_method_args': ['size', 'p', 'options'],
 'type_method_formals': ['IntList size',
                         'double p',
                         'const TensorOptions & options'],
 'with_gil': False}
```

**Comment by SsnL** [comment]
cc @zdevito

**Comment by SsnL** [comment]
Similarly failing for 
```yaml
- func: bernoulli_like(Tensor self, double p, *, TensorOptions options={}) -> Tensor
  variants: function

- func: bernoulli_like(Tensor self, Tensor p, *, TensorOptions options={}) -> Tensor
  variants: function
```
