### ISSUE TITLE
Nan is output by GRU on mps

### ISSUE THREAD

**Issue by kodecreer** [pytorch/pytorch#94691]
### 🐛 Describe the bug

When I use the mps it turns into nan values for just a simple encoder similar to the tutorial on PyTorch.org. This was after I tried converting the tensors to float32.
```
class Encoder(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers=1):
        super(Encoder, self).__init__()
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.embedding = nn.Embedding(input_size, hidden_size)
        self.gru = nn.GRU(hidden_size, hidden_size, num_layers, batch_first=True)
    
    def forward(self, x, hidden=None):
        embedded = self.embedding(x)
   
        output, hidden = self.gru(embedded, hidden)
        #the output and the hidden is nan
        return output, hidden
`

I just got the input that is basically a tokenized text from the basic_english and build vocab from iterator in torch text library.  The embedded works fine but after I feed the embedding into the GRU it just turns into nan values.

### Versions

This uses torch text and torch library.

**Comment by rojas-diego** [comment]
I've experienced similar issues with recurrent networks (RNN, LSTM, GRU) using Adam, CELoss and the built-in modules for these architectures with `torch==2.0.0`. At some point during training, gradients and activations become `NaN`. Some absurdly high loss values can be observed right before the issue arises. Running the exact same configuration on the CPU or on a CUDA GPU produces valid results and the training works as expected.

Excited for someone to shed light on this!

**Comment by alexdremov** [comment]
> I've experienced similar issues with recurrent networks (RNN, LSTM, GRU) using Adam, CELoss and the built-in modules for these architectures with `torch==2.0.0`. At some point during training, gradients and activations become `NaN`. Some absurdly high loss values can be observed right before the issue arises. Running the exact same configuration on the CPU or on a CUDA GPU produces valid results and the training works as expected.
> 
> Excited for someone to shed light on this!

Hey!
I've fixed LSTM some time ago; it should be fully consistent with CPU implementation. I was able to develop several projects with it without any problems. If loss explodes, try smaller learning rates.

GRU is still not functioning indeed. Hope that torch team could fix it in the near future

**Comment by dsm-72** [comment]
@alexdremov still experiencing this

**Comment by dsm-72** [comment]
@alexdremov in addition, there is a bug with `nn.LSTM` on `mps` that I can reproduce.

```
File ~/mambaforge/envs/MY_ENV/lib/python3.10/site-packages/torch/autograd/__init__.py:200, in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables, inputs)
    195     retain_graph = create_graph
    197 # The reason we repeat same the comment below is that
    198 # some Python versions print out the first line of a multi-line function
    199 # calls in the traceback and some print out the last line
--> 200 Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
    201     tensors, grad_tensors_, retain_graph, create_graph, inputs,
    202     allow_unreachable=True, accumulate_grad=True)

RuntimeError: Expected a proper Tensor but got None (or an undefined Tensor in C++) for argument #0 'grad_y'
```

Thank you @kodecreer  for this. I was getting extremely frustrated trying to figure out why my seq2seq worked in almost all cases except this.

**Comment by dsm-72** [comment]
@alexdremov  Here is my env file
```yml
name: MY_ENV
channels:
  - pytorch
  - conda-forge  
  - fastai
  - bioconda  

dependencies:  
  - python>=3.10

 # Utilities
 # -------------------------------------------------------------------------
  - tqdm
  - rich
  - typer

  # Jupyter Notebook
  # -------------------------------------------------------------------------
  - conda-forge::notebook
  - conda-forge::ipykernel
  - conda-forge::ipywidgets
  - conda-forge::jupyter_contrib_nbextensions
  
  # nbdev
  # -------------------------------------------------------------------------
  - fastai::nbdev>=2.3.12

  # PyTorch & Deep Learning
  # -------------------------------------------------------------------------
  - pytorch>=2
  - conda-forge::pytorch-lightning
  - 
  # Plotting
  # -------------------------------------------------------------------------
  - conda-forge::matplotlib
  - conda-forge::seaborn
  
  # Data Wrangling
  # -------------------------------------------------------------------------
  - conda-forge::scikit-learn
  - pandas>=2
  - numpy
  - scipy
    
  # Single-Cell
  # -------------------------------------------------------------------------
  - conda-forge::scanpy
  - bioconda::scprep
  

  # Pip / non-conda packages
  # -------------------------------------------------------------------------
  - pip
  - pip: 
    - magic-impute
    - phate
   
    ```
